package com.shadowhawk.registrar.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.shadowhawk.registrar.service.reservations.range.RangeReservationRequest;

import lombok.Data;
import lombok.NonNull;

/**
 * Represents an entry in our range reservation database
 */
@Data
@DynamoDBTable(tableName = "Reservations")
public class Reservation {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "memberId")
    private String memberId;

    @DynamoDBAttribute(attributeName = "rangeNum")
    private Integer rangeNum;

    @DynamoDBAttribute(attributeName = "mm")
    private Integer month;

    @DynamoDBAttribute(attributeName = "dd")
    private Integer day;

    @DynamoDBAttribute(attributeName = "yyyy")
    private Integer year;
}