package com.shadowhawk.registrar.model.dynamodb;

import java.util.List;
import org.apache.commons.lang3.StringUtils;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

/**
 * Represents a user of our services.
 */
@Data
@DynamoDBTable(tableName = "users")
public class User {
    /**
     * Uniquely identifies this user's account on our app.
     */
    @JsonProperty
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "accountId")
    private String accountId;

    /**
     * Uniquely identifies the business/company that this account represents
     */
    @JsonProperty
    @DynamoDBHashKey(attributeName = "businessId")
    private String businessId;
    
    /**
     * List of locations that this business operates
     */
    @JsonProperty
    @DynamoDBHashKey(attributeName = "facilities")
    private List<Facility> facilities;

    /**
     * Contains a list of all reservations made at this business
     */
    @JsonProperty
    @DynamoDBHashKey(attributeName = "reservations")
    private List<Reservation> reservations;

    private List<Partner> partners;

    @JsonProperty(required = true)
    @DynamoDBAttribute(attributeName = "timeCreated")
    private Long timeCreated;

    @DynamoDBVersionAttribute
    @JsonProperty(required = true)
    @DynamoDBAttribute(attributeName = "lastModified")
    private Long lastModified;

    /**
     * Given a facility ID that this business operates, return its latitude and longitude
     * @apiNote This method assumes that the facility ID you give belongs to this user
     * @return The coordinate string (e.g: "129.939135N 325326.23000E")
     */
    public String getFacilityCoordinates(final String facilityId){
        String result = null;

        //If the coordinates were not found for this facility ID, this is a serious data integrity issue!
        if(StringUtils.isBlank(result)){
            throw new IllegalStateException();
        }
        return result;
    }
}
